openapi: 3.0.0
info:
  title: Cookoff Backend API
  description: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /signup:
    post:
      summary: User signup
      description: Creates a user and sends a generated password through mail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupRequest"
      responses:
        "200":
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignupResponse"
        "400":
          description: Invalid request payload
        "406":
          description: Validation failed
        "409":
          description: User already exists
        "500":
          description: Internal server error

components:
  schemas:  
    SignupRequest:
      type: object
      required:
        - email
        - name
        - reg_no
      properties:
        email:
          type: string
          format: email
        name:
          type: string
        reg_no:
          type: string

    SignupResponse:
      type: object
      properties:
        message:
          type: string
          example: user added
        email:
          type: string
          description: User Email
          example: test@example.com
        password:
          type: string
          description: Generated plain password
          example: test123
