openapi: 3.0.0
info:
  title: Cookoff Backend API
  description: API Documentation
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /signup:
    post:
      summary: User signup
      description: Creates a user and sends a generated password through mail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupRequest"
      responses:
        "200":
          description: User successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignupResponse"
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/ErrorResponse"
        "406":
          description: Validation failed
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: User already exists
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/ErrorResponse"
  
  /login:
    post:
      summary: User login
      description: Authenticates a user with email and password, sets cookies for access and refresh tokens, and returns user data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "400":
          description: Invalid request payload
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/ErrorResponse"
        "406":
          description: Validation failed
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: User not found
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/ErrorResponse"
        "409":
          description: Invalid password
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
               $ref: "#/components/schemas/ErrorResponse"
  /questions:
    get:
      summary: Get all questions
      operationId: getAllQuestions
      responses:
        "200":
          description: List of all questions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Question"
        "500":
          description: Server error
    post:
      summary: Create a new question
      operationId: createQuestion
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateQuestionParams"
      responses:
        "201":
          description: Question created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Question"
        "400":
          description: Invalid input
        "500":
          description: Server error

  /questions/{id}:
    get:
      summary: Get a question by ID
      operationId: getQuestion
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Question details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Question"
        "400":
          description: Invalid UUID
        "404":
          description: Question not found
    put:
      summary: Update a question
      operationId: updateQuestion
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateQuestionParams"
      responses:
        "200":
          description: Updated successfully
        "400":
          description: Invalid request
        "500":
          description: Server error
    delete:
      summary: Delete a question
      operationId: deleteQuestion
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Deleted successfully
        "400":
          description: Invalid UUID
        "500":
          description: Server error

  /questions/{id}/bounty/activate:
    put:
      summary: Activate bounty on a question
      operationId: activateBounty
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Bounty activated
        "400":
          description: Invalid UUID
        "500":
          description: Server error

  /questions/{id}/bounty/deactivate:
    put:
      summary: Deactivate bounty on a question
      operationId: deactivateBounty
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Bounty deactivated
        "400":
          description: Invalid UUID
        "500":
          description: Server error


components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        status:
          type: string
          example: "failed"
        error:
          type: string
          description: Error Message
    
    SignupRequest:
      type: object
      required:
        - email
        - name
        - reg_no
      properties:
        email:
          type: string
          format: email
        name:
          type: string
        reg_no:
          type: string

    SignupResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
        message:
          type: string
          example: user added
        email:
          type: string
          description: User Email
          example: test@example.com
        password:
          type: string
          description: Generated plain password
          example: test123

    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password

    LoginResponse:
      type: object
      properties:
        status:
          type: string
          example: "success"
        message:
          type: string
          example: "Login successful"
        data:
          type: object
          properties:
            username:
              type: string
              description: User's display name
              example: Chef
            round:
              type: integer
              description: Round qualified (0 or 1)
              example: 1
            score:
              type: string
              description: User score (numeric type from Postgres)
              example: 100
    Question:
      type: object
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
        title:
          type: string
        qType:
          type: string
        isBountyActive:
          type: boolean
        inputFormat:
          type: array
          items: { type: string }
        points:
          type: integer
        round:
          type: integer
        constraints:
          type: array
          items: { type: string }
        outputFormat:
          type: array
          items: { type: string }
        sampleTestInput:
          type: array
          items: { type: string }
        sampleTestOutput:
          type: array
          items: { type: string }
        explanation:
          type: array
          items: { type: string }
      required:
        - id
        - description
        - title
        - qType
        - isBountyActive
        - inputFormat
        - points
        - round
        - constraints
        - outputFormat
        - sampleTestInput
        - sampleTestOutput
        - explanation

    CreateQuestionParams:
      type: object
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
        title:
          type: string
        qType:
          type: string
        isBountyActive:
          type: boolean
        inputFormat:
          type: array
          items: { type: string }
        points:
          type: integer
        round:
          type: integer
        constraints:
          type: array
          items: { type: string }
        outputFormat:
          type: array
          items: { type: string }
        sampleTestInput:
          type: array
          items: { type: string }
        sampleTestOutput:
          type: array
          items: { type: string }
        explanation:
          type: array
          items: { type: string }
      required:
        - id
        - description
        - title
        - qType
        - isBountyActive
        - inputFormat
        - points
        - round
        - constraints
        - outputFormat
        - sampleTestInput
        - sampleTestOutput
        - explanation

    UpdateQuestionParams:
      type: object
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
        title:
          type: string
        qType:
          type: string
        isBountyActive:
          type: boolean
        inputFormat:
          type: array
          items: { type: string }
        points:
          type: integer
        round:
          type: integer
        constraints:
          type: array
          items: { type: string }
        outputFormat:
          type: array
          items: { type: string }
        sampleTestInput:
          type: array
          items: { type: string }
        sampleTestOutput:
          type: array
          items: { type: string }
        explanation:
          type: array
          items: { type: string }
      required:
        - id
        - description
        - title
        - qType
        - isBountyActive
        - inputFormat
        - points
        - round
        - constraints
        - outputFormat
        - sampleTestInput
        - sampleTestOutput
        - explanation
